version: 2

before:
  hooks:
    - go mod download
    - /bin/bash -c "rm -rf third_party && GOWORK=off go run github.com/google/go-licenses/v2@v2.0.1 save --force --ignore wsfs ./cmd/wsfs --save_path third_party"

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/wsfs
    binary: wsfs
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .ShortCommit }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["tar.gz"]
    name_template: 'wsfs_{{ .Os }}_{{ .Arch }}'
    files:
      - src: third_party
        dst: third_party

nfpms:
  - package_name: wsfs
    file_name_template: 'wsfs_{{ .ShortCommit }}_linux_{{ .Arch }}'
    formats:
      - deb
    dependencies:
      - fuse3
    contents:
      - src: packaging/systemd/wsfs@.service
        dst: /usr/lib/systemd/user/wsfs@.service
      - src: packaging/systemd/wsfs.env.example
        dst: /usr/share/doc/wsfs/wsfs.env.example
      - src: third_party
        dst: /usr/share/doc/wsfs/third_party

checksum:
  name_template: 'wsfs_SHA256SUMS'
  algorithm: sha256

snapshot:
  version_template: '1~{{ .ShortCommit }}'

release:
  disable: true
